<%-- /* str = 
		"<table id='favor_table' class='table table-bordered'>                                                                                                          "
		+"	<tr class='active'>                                                                                                                                         "
		+"		<th style='text-align: center;'>상태</th>                                                                                                                "
		+"		<th style='text-align: center;'>회사명</th>                                                                                                               "
		+"		<th style='text-align: center;'>공고 제목</th>                                                                                                             "
		+"		<th style='text-align: center; width: 90px;'>모집기간</th>                                                                                                 "
		+"		<th style='width: 65px;'>조회수</th>                                                                                                                      "
		+"		<th style='text-align: center;'>관리</th>                                                                                                                "
		+"	</tr>                                                                                                                                                       "
		+"	<c:forEach items='${CRecruitVOList}' var='CRecruitVO' varStatus='status'>                                                                                   "
		+"		<c:if test=${CRecruitVO.acceptmethod=='모집중'}>                                                                                                           "
		+"			<tr>                                                                                                                                                "
		+"				<td style='text-align: center;'>                                                                                                                "
		+"				<input type='hidden' value='${CRecruitVO.acceptmethod}'}>                                                                                       "
		+"				<span class='acceptmethod badge badge-pill'>${CRecruitVO.acceptmethod}</span></td>			                                                    "
		+"				<td style='text-align: center;'>${CRecruitVO.recruitform}</td>                                                                                  "
		+"				<td style='text-align: center;'>                                                                                                                "
		+"					<a href='/company/C_recruitMent?recruitNum=${CRecruitVO.bno}' onClick='window.open(this.href, '', 'width=1240, height=960'); return false;'>"
		+"					${CRecruitVO.bno} : ${CRecruitVO.title}</a>                                                                                                 "
		+"				</td>                                                                                                                                           "
		+"				<td style='text-align: center;'>${CRecruitVO.regdate}<br>~<br>${CRecruitVO.jobdesc}</td><!-- jobdesc가 period -->                                "
		+"				<td style='text-align: center;'><span class='badge badge-pill'>${CRecruitVO.viewcnt}</span></td>                                                "
		+"				<td style='text-align: center;'>                                                                                                                "
		+"				<input type='hidden' id='rcno${status.index}' value='${CRecruitVO.bno}' />                                                                      "
		+"					<img src=/resources/rpjt/img/on.png id='non' name='clipping_cancel' onclick='clipping_cancel_function(rcno${status.index}.value)'>          "
		+"					</td>                                                                                                                                       "
		+"			</tr>                                                                                                                                               "
		+"		</c:if>                                                                                                                                                 "
		+"	</c:forEach>                                                                                                                                                "
		+"</table>       --%>